# Generated by Django 4.1.2 on 2022-10-17 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='Наименование организации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('age', models.IntegerField(max_length=3, verbose_name='Возраст')),
                ('worker_id', models.IntegerField(max_length=10, verbose_name='Номер сотрудника')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фотография сотрудника')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facerecognition.organization')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
