# Generated by Django 4.1.2 on 2022-10-20 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id_organization', models.IntegerField(primary_key=True, serialize=False, verbose_name='Наименование организации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id_worker', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер сотрудника')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фотография сотрудника')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facerecognition.organization')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
