# Generated by Django 4.1.2 on 2022-10-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0002_alter_worker_age_alter_worker_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='id',
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер сотрудника'),
        ),
    ]
