# Generated by Django 4.1.2 on 2022-10-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognition', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id_organization',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер организации'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id_worker',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер сотрудника'),
        ),
    ]
